#!/bin/sh
clang-format -i *.hpp
clang-format -i examples/hello-world/*.cpp
clang-format -i examples/mat-inv-nsa/*.cpp
clang-format -i examples/mat-vec-multiplication/*.cpp
clang-format -i examples/mat-write-col/*.cpp
clang-format -i examples/task-level-pipelining/*.cpp
echo "Finished formatting 'flames'!"
